### ISSUE TITLE
Extending the sda-commons-server-auth OPAFilter

### ISSUE THREAD

**Issue by cawado** [SDA-SE/sda-dropwizard-commons#197]
In our project we need to pass some query/body parameters to the OPA sidecar. 

Therefore the filter and its config needs to be extended, like we did in our current fork. Have a look at [forked Repository Branch](https://github.com/cawado/sda-dropwizard-commons/tree/feat/extended-opa-auth/sda-commons-server-auth)

If there's a general interest, I'll create a pull request.

**Comment by dhenneke** [comment]
Hi Raimund, thanks for your sharing your ideas and your proposal. I had a look on your changes and I am not sure if these features should be activated for all services by default. In general, we think that the authorization API definition (=the inputs that are sent to the OPA and the constraints that are returned from the OPA) of a service should be part of its functional behavior and not necessarily configurable during runtime. We also not completely convinced have body contents handled in the OPA. However, we acknowledge the need to extend the input for certain specific use cases.

In order to allow such extensions, I created #200 to make the `OpaInput` extendable without needing to fork the library in the future, like you did. The existing headers functionality was converted to an `OpaInputExtension` and can be optionally disabled. You could now create new extensions that add your needed input (only selected headers, query parameters, body parameters) directly in your service or in a separate independent library if your project has a need for this.

With this approach, we can also think about including more extensions directly in this library if valuable for a large number of services. I also started to build an extension to make the query parameters accessible in the OPA, but I decided to not include it in the pull request yet.

My pull request has not been reviewed or merged yet, so feel free to give feedback. What do you think about the approach?

**Comment by cawado** [comment]
Hey Dominik,
thanks for your feedback. 
I really like the extension approach. 

As mentioned by Joerg, it could be changed to a functional interface when you 
- extend the inputExtensions from List to Map with namespace as key and 
- the withInputExtension method as withInputExtension(String namespace, InputExtension). 

I'm really looking forward to it. 
Any idea when it will be merged? 

Cya 
Raimund

**Comment by dhenneke** [comment]
The PR was merged and the change is available in version [0.80.0](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/0.80.0). Can we close this issue?

We also extended the documentation regarding some issues we saw when accessing the body in such an extension or the general work with headers or query parameters.

**Comment by cawado** [comment]
Looks nice. 
Thank you for this nice extension.
