### ISSUE TITLE
FeatureRequest: Make SwaggerBundle use a SwaggerConfig

### ISSUE THREAD

**Issue by cawado** [SDA-SE/sda-dropwizard-commons#443]
Hey there. 

Instead of config the SwaggerBundle as inline code: 
``` diff
bootstrap.addBundle(SwaggerBundle.builder()
-        .withTitle("Service title")
-        .withVersion("1.0")
-        .withDescription("service description")
-        .withContact("XYZ Core Team", "example@xyz.de")
-        .withTermsOfServiceUrl("http://terms.of.service")
        .addResourcePackageClass(getClass())
        .build());
    }
``` 
it should be something like: 
``` diff
bootstrap.addBundle(SwaggerBundle.builder()
+    .withSwaggerConfigProvider(MainConfiguration::getSwagger)
    .addResourcePackageClass(getClass())
    .build());
```
with coresponding SwaggerConfig, like you did in other bundles.

**Comment by JoergSiebahn** [comment]
Thanks for your request. There are many options how Swagger documentation could be included in a service. The chosen builder pattern is the one we thought is the best fo SDA Commons. But that was a few years ago.

As far as I remember, adding parts of the Swagger documentation to the configuration was not on our list. It feels wrong to me, to add documentation to a configuration file that can be changed in a released artifact.

When using an API first approach it may be an option to create an API specification as Swagger file or copy a given API specification to the code base and load it at runtime. In that case, the IDE can help with a JSON Schema to edit the spec. This won't be possible with the config.yaml file.

To document a service with a code first approach, another option would be to use the Swagger annotations. Most of the Swagger specification can be documented by annotations. We originally decided against using only the annotations, because this strict builder pattern should help developers to add all mandatory information that is needed to describe the service and get in contact with the developers of the service. Although this can be achieved using a configuration class with mandatory fields as well, the builder pattern gives more guidance.

But maybe it is time to rethink what is the best approach and we find better options to fulfill all needs.

Could you give some more information about your use case? What do you want to achieve?
Is there something that is impossible to do with the current implementation?

**Comment by cawado** [comment]
Hey Joerg. 
Sorry for the late response. 

With the current implementation I can do everything I need at the moment, but it feels wrong to configure everything in the config.yml except the swagger-bundle details. 
If you thing it's ok to code this information in the MainApplication.java instead, feel free to close this issue. 

Cya
Raimund

**Comment by dhenneke** [comment]
We are closing this issue because we don't want to change the configuration of the SwaggerBundle. We don't think that the swagger details should be configurable by the `config.yml` since they are fixed during design/compile time of a service. The configuration class is more suited for deployment-time configurations. Furthermore, we will promote OpenAPI 3.0 to be the default in the future and won't add new features to the swagger bundle.

In the new [OpenAPI 3.0 bundle](https://github.com/SDA-SE/sda-dropwizard-commons/tree/master/sda-commons-server-openapi), we even removed the builder-configuration completely. Instead, one should use the [`@OpenAPIDefinition`](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#OpenAPIDefinition) annotation on one of your classes or use a skeleton-openapi-3 file.
